spring.application.name=spring-ai-demo
server.port=9090
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-3.5-turbo

#spring.ai.model.chat=ollama
#spring.ai.ollama.chat.options.model=llama3.2:1b
